name: Test

on:
  push:
    branches:
      - master

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Run action
        uses: ./ # Uses an action in the root directory
        id: del_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: true
          include-prerelease: true
          semver-loose: true
          remove-tags: true
          dry-run: true
          version-prefix: ''

  call_reusable_workflow:
    needs: build_and_run
    uses: bartonmalow/delete-old-releases/.github/workflows/version.yml@master
    with:
         ß GH_PAT: ${{ secrets.GH_PAT }}