name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Run action
        uses: ./ # Uses an action in the root directory
        id: del_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: true
          include-prerelease: true
          semver-loose: true
          remove-tags: true
          dry-run: true
          version-prefix: ''

      - name: Version the release
        if: success()
        uses: bartonmalow/delete-old-release/.github/workflows/version.yml@main
        with:
            GH_PAT: ${{ secrets.GH_PAT }}